CREATE OR REPLACE TRANSIENT TABLE STAGING_PATIENT_RECORDS (
PATIENT_ID NUMBER,
FIRST_NAME VARCHAR,
LAST_NAME VARCHAR,
DIAGNOSIS VARCHAR,
ADMISSIONDATE DATE,
DISCHARGEDATE DATE,
STATUS VARCHAR
);

CREATE OR REPLACE STREAM STAGING_PATIENT_RECORDS_STREAM ON TABLE STAGING_PATIENT_RECORDS;

CREATE OR REPLACE TABLE PATIENT_RECORDS 
(
PATIENT_ID NUMBER,
FIRST_NAME VARCHAR,
LAST_NAME VARCHAR,
DIAGNOSIS VARCHAR,
ADMISSIONDATE DATE,
DISCHARGEDATE DATE,
STATUS VARCHAR
);

CREATE OR REPLACE TASK LoadIncrementalPatientRecords
WAREHOUSE = 'COMPUTE_WH'
SCHEDULE = '2 MINUTE' 
WHEN SYSTEM$STREAM_HAS_DATA('STAGING_PATIENT_RECORDS_STREAM') 
AS 
MERGE INTO PATIENT_RECORDS PR USING STAGING_PATIENT_RECORDS_STREAM SPRS ON (
PR.PATIENT_ID = SPRS.PATIENT_ID
)
WHEN MATCHED AND SPRS.METADATA$ACTION = 'INSERT' THEN 
UPDATE SET PR.STATUS = SPRS.STATUS
WHEN NOT MATCHED AND SPRS.METADATA$ACTION = 'INSERT' THEN 
INSERT 
(
PATIENT_ID,
FIRST_NAME,
LAST_NAME,
DIAGNOSIS,
ADMISSIONDATE,
DISCHARGEDATE,
STATUS
)
VALUES
(
SPRS.PATIENT_ID,
SPRS.FIRST_NAME,
SPRS.LAST_NAME,
SPRS.DIAGNOSIS,
SPRS.ADMISSIONDATE,
SPRS.DISCHARGEDATE,
SPRS.STATUS
);

ALTER TASK LoadIncrementalPatientRecords RESUME;


--After processing the file patient_records_20241130082515.csv


SELECT * FROM STAGING_PATIENT_RECORDS;

SELECT * FROM STAGING_PATIENT_RECORDS_STREAM;

SELECT * FROM PATIENT_RECORDS;

--After processing the file patient_records_20241130083215.csv
--with updates on couple of records and inserts

SELECT * FROM STAGING_PATIENT_RECORDS;

SELECT * FROM STAGING_PATIENT_RECORDS_STREAM;

SELECT * FROM PATIENT_RECORDS;

ALTER TASK LoadIncrementalPatientRecords SUSPEND;

ALTER TABLE PATIENT_RECORDS CLUSTER BY (ADMISSIONDATE);

SELECT SYSTEM$CLUSTERING_INFORMATION('PATIENT_RECORDS');

SELECT * FROM PATIENT_RECORDS WHERE ADMISSIONDATE BETWEEN '2024-08-26' AND CURRENT_DATE();

select start_time, end_time, credits_used, num_bytes_reclustered, table_name, schema_name, database_name
from snowflake.account_usage.AUTOMATIC_CLUSTERING_HISTORY
where database_name = 'TEST_DB'
  and schema_name = 'HOSPITAL'
  and table_name = 'PATIENT_RECORDS';

select system$clustering_depth('TEST_DB.HOSPITAL.PATIENT_RECORDS');

select system$clustering_information('TEST_DB.HOSPITAL.PATIENT_RECORDS', '(ADMISSIONDATE)'); 